/** English for the ProtoCap map, keyed by its French strings (see protocap-map.js). */
const dictionary: Record<string, string> = {
  Calme: 'Calm',
  "NIVEAU D'ATTENTION · 0": 'ATTENTION LEVEL · 0',
  "Rien à décider. Traitement neutre, faible contraste : l'élément s'efface pour laisser la place à ce qui compte.":
    'Nothing to decide. Neutral treatment, low contrast: the element recedes to leave room for what matters.',
  'À surveiller': 'Watch',
  "NIVEAU D'ATTENTION · 1": 'ATTENTION LEVEL · 1',
  'Attention sans action immédiate. Accent doux, contraste mesuré.':
    'Attention without immediate action. Soft accent, measured contrast.',
  'À traiter': 'Act on',
  "NIVEAU D'ATTENTION · 2": 'ATTENTION LEVEL · 2',
  'Action attendue. Accent affirmé mais sobre, position prioritaire dans la lecture.':
    'Action expected. Firm but restrained accent, priority position in the reading order.',
  Critique: 'Critical',
  "NIVEAU D'ATTENTION · 3": 'ATTENTION LEVEL · 3',
  'Enjeu réel et urgent. Contraste fort par la place et la position, sans saturation extrême ni clignotement.':
    'Real, urgent stakes. Strong contrast through placement and position, without extreme saturation or blinking.',
  'Carte interactive de ProtoCap : surfaces, Céline, frontières de confiance, stockage, packing, logistique, péremption et qualité':
    'Interactive map of ProtoCap: surfaces, Céline, trust boundaries, storage, packing, logistics, expiry and quality',
  'Vues de la carte': 'Map views',
  'Lancer ou arrêter le parcours guidé': 'Start or stop the guided tour',
  PARCOURIR: 'TOUR',
  'SURVOLER · CLIQUER': 'HOVER · CLICK',
  ARRÊTER: 'STOP',
  'Activer ou couper les animations': 'Turn animations on or off',
  INTERACTIF: 'INTERACTIVE',
  "Qu'est-ce qui est réel, simulé ou local ?": 'What is real, simulated or local?',
  "Vue d'ensemble : les huit surfaces de ProtoCap classées par statut":
    "Overview: ProtoCap's eight surfaces sorted by status",
  Transparence: 'Transparency',
  'Réel · local · fictif · statique': 'Real · local · fictional · static',
  "Démonstrateur d'ingénierie": 'Engineering demonstrator',
  "Huit surfaces qui déclarent honnêtement leur statut : ce qui passe par un serveur, ce qui reste dans le navigateur, ce qui est fictif. Le dépôt documente ce que chaque démonstration prouve — et ce qu'elle ne prétend pas prouver.":
    'Eight surfaces that state their status honestly: what goes through a server, what stays in the browser, what is fictional. The repository documents what each demo proves — and what it does not claim to prove.',
  'Serveur protégé': 'Protected server',
  'Surface · serveur protégé': 'Surface · protected server',
  "Guide de procédures de poste dont le contenu est protégé : le code est vérifié côté serveur, qui émet une session ; sans elle, la configuration protégée n'est jamais livrée. Une variante de démonstration isolée existe, sur données fictives.":
    'Workstation procedure guide with protected content: the code is checked server-side, which issues a session; without it, the protected configuration is never delivered. An isolated demo variant exists, on fictional data.',
  Serveur: 'Server',
  'Démo isolée': 'Isolated demo',
  "Assistante IA du poste, médiée par le serveur : la clé du fournisseur et le prompt restent côté serveur, et un moteur de domaine résout d'abord les cas routiniers sans appel externe. Pas d'IA hors ligne, aucun pilotage d'équipement.":
    "The workstation's AI assistant, mediated by the server: the provider key and the prompt stay server-side, and a domain engine resolves routine cases first with no external call. No offline AI, no equipment control.",
  'Surface · local au navigateur': 'Surface · local to the browser',
  'Workflow interactif de validité et de statut, avec historique local. Il ne prétend ni base qualité partagée, ni dossier de lot électronique validé, ni synchronisation entre appareils.':
    'Interactive validity and status workflow, with local history. It claims no shared quality database, no validated electronic batch record, and no cross-device sync.',
  Navigateur: 'Browser',
  "Cycle de vie d'une demande, priorisation, temps écoulé et transitions de statut — dans le navigateur. Aucun envoi vers un autre poste, ni websocket, ni temps réel.":
    'Request lifecycle, prioritization, elapsed time and status transitions — in the browser. Nothing is sent to another station: no websocket, no real time.',
  'Machine à états': 'State machine',
  "Calculs de conditionnement déterministes et suivi manuel des expéditions par palette. Pas d'ERP ni de données maîtres, pas d'état partagé, pas d'exécution automatique d'ordre de fabrication.":
    'Deterministic packing calculations and manual per-pallet shipment tracking. No ERP or master data, no shared state, no automatic execution of production orders.',
  'Entiers sûrs': 'Safe integers',
  Fictif: 'Fictional',
  'Surface · données fictives': 'Surface · fictional data',
  "Visualisation opérationnelle par rôle, alimentée par une fixture du dépôt (linePulseMock.json). Ce n'est ni de la télémétrie ni du temps réel : c'est de l'UX d'aide à la décision.":
    'Role-based operational visualization, fed by a repository fixture (linePulseMock.json). It is neither telemetry nor real time: it is decision-support UX.',
  'Données fictives': 'Fictional data',
  Statique: 'Static',
  'Surface · statique': 'Surface · static',
  "Modèle de recherche et de navigation pour des références opérationnelles. Non connecté à une GED d'entreprise.":
    'Search and navigation model for operational references. Not connected to an enterprise document system.',
  'Proposition de pilote': 'Pilot proposal',
  "Proposition structurée d'un pilote contrôlé, avec ses garde-fous. Ce n'est ni une approbation, ni un déploiement, ni des gains mesurés : les bénéfices annoncés sont des hypothèses.":
    'A structured proposal for a controlled pilot, with its guardrails. It is not an approval, a rollout or measured gains: the stated benefits are hypotheses.',
  Hypothèses: 'Hypotheses',
  'Statut · serveur protégé': 'Status · protected server',
  'Ce qui exige un serveur': 'What requires a server',
  "ShiftGuide et Céline dépendent du serveur : déverrouillage, validation de session, clé de fournisseur et prompt protégés. C'est aussi ce qui exige de la connectivité — ProtoCap ne se présente donc pas comme entièrement hors ligne.":
    'ShiftGuide and Céline depend on the server: unlock, session validation, protected provider key and prompt. That is also what requires connectivity — so ProtoCap does not present itself as fully offline.',
  'Local au navigateur': 'Local to the browser',
  'Statut · local au navigateur': 'Status · local to the browser',
  'Ce qui ne quitte pas le navigateur': 'What never leaves the browser',
  "Expiry Check, Logistics Call et Packing utilisent le stockage du navigateur : c'est autonome, mais cela ne crée aucune source de vérité partagée entre utilisateurs ou appareils.":
    'Expiry Check, Logistics Call and Packing use browser storage: they are self-contained, but create no shared source of truth across users or devices.',
  'Statut · données fictives': 'Status · fictional data',
  'Ce qui est simulé, et dit comme tel': 'What is simulated, and said to be',
  "Les données publiques de démonstration sont volontairement fictives. Les gains ou KPI cités dans les documents sont des hypothèses de conception ou des critères d'évaluation, sauf mention explicite de mesure.":
    'The public demo data is deliberately fictional. Gains or KPIs cited in the documents are design hypotheses or evaluation criteria, unless a measurement is explicitly stated.',
  'Statut · statique': 'Status · static',
  'Ce qui est contenu, pas système': 'What is content, not system',
  "La base de connaissance et la proposition de pilote décrivent un modèle ou une démarche : elles ne se branchent sur aucun système d'entreprise.":
    'The knowledge base and the pilot proposal describe a model or an approach: they plug into no enterprise system.',
  'Qui écrit la réponse : le modèle ou le serveur ?':
    'Who writes the answer: the model or the server?',
  'Céline : moteur de domaine, garde de coûts et autorité du serveur':
    'Céline: domain engine, cost guard and server authority',
  Autorité: 'Authority',
  'Le modèle choisit, le serveur écrit': 'The model chooses, the server writes',
  'Chemin 1 · déterministe': 'Path 1 · deterministic',
  'Routine : le moteur de domaine': 'Routine: the domain engine',
  "Le moteur tente d'abord de résoudre l'interaction sans modèle. S'il y parvient, aucun appel fournisseur n'a lieu.":
    'The engine first tries to resolve the interaction without a model. If it succeeds, no provider call is made.',
  '0 appel IA': '0 AI calls',
  'Chemin 2 · sémantique': 'Path 2 · semantic',
  'Ambigu : vers le fournisseur': 'Ambiguous: to the provider',
  'Seule une interaction sémantique non résolue continue vers la garde de coûts, puis vers le fournisseur.':
    'Only an unresolved semantic interaction goes on to the cost guard, then to the provider.',
  Repli: 'Fallback',
  Entrée: 'Input',
  "Un message d'opérateur": 'An operator message',
  "Le message part vers /api/celine/chat. Vers le chemin fournisseur, il est borné à 2 000 caractères et l'historique à quatre tours.":
    'The message goes to /api/celine/chat. On the provider path, it is capped at 2,000 characters and the history at four turns.',
  '≤ 2 000 car.': '≤ 2,000 chars',
  'réponse déterministe': 'deterministic answer',
  Sortie: 'Output',
  'Réponse du moteur de domaine': 'Domain engine answer',
  "Une réponse résolue localement traverse directement jusqu'à la composition finale.":
    'An answer resolved locally goes straight through to the final composition.',
  'Sans fournisseur': 'No provider',
  'autorisé ?': 'allowed?',
  Contrôle: 'Check',
  'Admission par la garde': 'Admission by the guard',
  "Une requête bloquée par la garde n'atteint jamais DeepSeek : elle ressort en échec local (rate_limited ou budget_exceeded).":
    'A request blocked by the guard never reaches DeepSeek: it comes back as a local failure (rate_limited or budget_exceeded).',
  décision: 'decision',
  'Fournisseur → serveur': 'Provider → server',
  'Une décision structurée': 'A structured decision',
  "Le modèle ne fournit qu'une décision ; il n'écrit pas la réponse finale destinée à l'opérateur.":
    'The model provides only a decision; it does not write the final answer meant for the operator.',
  '160 jetons max': '160 tokens max',
  'Décision validée': 'Validated decision',
  'Une décision valide est acceptée puis convertie en réponse par le serveur.':
    'A valid decision is accepted, then turned into an answer by the server.',
  Validée: 'Validated',
  Rejet: 'Reject',
  'Décision invalide': 'Invalid decision',
  "Une décision invalide n'est jamais appliquée telle quelle : le modèle ne peut pas écrire directement à l'opérateur.":
    'An invalid decision is never applied as is: the model cannot write directly to the operator.',
  Rejetée: 'Rejected',
  Opérateur: 'Operator',
  'Étape 01': 'Step 01',
  "L'opérateur pose une question": 'The operator asks a question',
  'Une question en langage naturel sur sa procédure de poste, depuis ShiftGuide. La conversation exige une session valide : sans elle, la route répond 401.':
    'A natural-language question about their workstation procedure, from ShiftGuide. The chat requires a valid session: without one, the route returns 401.',
  'Session requise': 'Session required',
  'Session · limites': 'Session · limits',
  'Étape 02 · Express': 'Step 02 · Express',
  "Le serveur vérifie d'abord": 'The server checks first',
  'Il authentifie la session ShiftGuide et applique les limites de requêtes — 60 par minute et par IP, 30 par session — avant tout autre travail.':
    'It authenticates the ShiftGuide session and applies request limits — 60 per minute per IP, 30 per session — before any other work.',
  '401 sans session': '401 without session',
  '429 au-delà': '429 beyond',
  'Moteur de domaine': 'Domain engine',
  'Étape 03a · déterministe': 'Step 03a · deterministic',
  'Le moteur de domaine': 'The domain engine',
  "Il tente de résoudre l'interaction de façon déterministe. S'il la traite, DeepSeek n'est pas appelé et les budgets fournisseur restent intacts : l'IA n'est pas le chemin par défaut.":
    'It tries to resolve the interaction deterministically. If it handles it, DeepSeek is not called and provider budgets stay intact: AI is not the default path.',
  Déterministe: 'Deterministic',
  'Garde de coûts': 'Cost guard',
  '8 appels / min': '8 calls / min',
  'Étape 03b · garde': 'Step 03b · guard',
  'Une garde avant le réseau': 'A guard before the network',
  "Avant tout travail réseau : taille du prompt et de l'historique, débit d'appels (8 par minute) et jetons déjà consommés (seuil de 100 000 par heure). Volontairement locale au processus : adaptée à une réplique unique.":
    'Before any network work: prompt and history size, call rate (8 per minute) and tokens already used (100,000 per hour threshold). Deliberately process-local: suited to a single replica.',
  '100 k jetons / h': '100k tokens / h',
  'Étape 04 · fournisseur': 'Step 04 · provider',
  'Une frontière de repli': 'A fallback boundary',
  "Le fournisseur est une frontière de classification linguistique de repli, pas un chemin d'exécution. Historique limité à quatre tours, complétion plafonnée à 160 jetons par défaut.":
    'The provider is a fallback linguistic-classification boundary, not an execution path. History capped at four turns, completion capped at 160 tokens by default.',
  '160 jetons': '160 tokens',
  '4 tours': '4 turns',
  Normalisation: 'Normalization',
  'Étape 05 · serveur': 'Step 05 · server',
  'Normaliser et valider': 'Normalize and validate',
  "La sortie du fournisseur est normalisée et validée. Seule une décision recevable passe à l'étape d'autorité ; le reste est rejeté.":
    'The provider output is normalized and validated. Only an admissible decision moves on to the authority step; the rest is rejected.',
  'Repli sûr': 'Safe fallback',
  "Sortie d'erreur": 'Error exit',
  "Rejet d'une décision invalide": 'Rejecting an invalid decision',
  "Une décision invalide n'est jamais appliquée : l'opérateur ne reçoit pas de texte libre écrit par le modèle.":
    'An invalid decision is never applied: the operator never receives free text written by the model.',
  'Jamais appliquée': 'Never applied',
  AUTORITÉ: 'AUTHORITY',
  'LE SERVEUR ÉCRIT': 'THE SERVER WRITES',
  'Étape 06 · autorité': 'Step 06 · authority',
  "Quel que soit le chemin, la réponse remise à l'opérateur est composée par le serveur. Le modèle ne renvoie qu'une décision structurée : il ne peut ni inventer une procédure, ni contourner la validation.":
    'Whatever the path, the answer delivered to the operator is composed by the server. The model returns only a structured decision: it can neither invent a procedure nor bypass validation.',
  'Forme de la réponse': 'Answer shape',
  'Une réponse structurée': 'A structured answer',
  "Le résultat final porte un message, une checklist et une suite proposée : trois champs que le serveur compose et que l'interface affiche.":
    'The final result carries a message, a checklist and a suggested follow-up: three fields the server composes and the interface displays.',
  scénario: 'scenario',
  'Scénario · routine': 'Scenario · routine',
  'Résolu sans modèle': 'Resolved, no model',
  "Une interaction routinière est résolue par le moteur de domaine : aucun appel fournisseur, budgets intacts. C'est le chemin visé pour l'essentiel des échanges.":
    'A routine interaction is resolved by the domain engine: no provider call, budgets intact. This is the intended path for most exchanges.',
  Ambigu: 'Unclear',
  'Scénario · ambigu': 'Scenario · ambiguous',
  'Le modèle est consulté': 'The model is consulted',
  'Une interaction sémantique non résolue passe par la garde de coûts, puis le fournisseur ; la décision est validée et le serveur écrit toujours la réponse.':
    'An unresolved semantic interaction goes through the cost guard, then the provider; the decision is validated and the server still writes the answer.',
  Garde: 'Guard',
  'Quel identifiant ouvre quelle porte ?': 'Which credential opens which door?',
  Frontières: 'Boundaries',
  'Frontières de confiance : identifiants, processus protégé et processus de démonstration':
    'Trust boundaries: credentials, protected process and demo process',
  Isolement: 'Isolation',
  'Un jeton ne vaut que pour son processus': 'A token is valid only for its own process',
  'Session démo': 'Demo session',
  'Aucun identifiant': 'No credential',
  'Code ShiftGuide': 'ShiftGuide code',
  'Jeton protégé': 'Protected token',
  'Jeton démo': 'Demo token',
  'PROCESSUS PROTÉGÉ': 'PROTECTED PROCESS',
  'PROCESSUS DÉMO': 'DEMO PROCESS',
  'Identifiant · aucun': 'Credential · none',
  "Un visiteur anonyme. Il ne peut franchir que la porte publique : créer une session sur l'origine de démonstration. Tout le reste répond 401 ou 404.":
    'An anonymous visitor. They can pass only the public door: creating a session on the demo origin. Everything else returns 401 or 404.',
  'Démo · session': 'Demo · session',
  'Le reste': 'The rest',
  'Identifiant · code': 'Credential · code',
  'Le code ShiftGuide': 'The ShiftGuide code',
  "Comparé côté serveur, limité à 10 tentatives par 10 minutes et par IP. Il n'ouvre que l'unlock du processus protégé — l'origine de démonstration ne l'expose pas (404).":
    "Compared server-side, limited to 10 attempts per 10 minutes per IP. It opens only the protected process's unlock — the demo origin does not expose it (404).",
  'Unlock protégé': 'Protected unlock',
  '10 essais / 10 min': '10 tries / 10 min',
  'Identifiant · session protégée': 'Credential · protected session',
  'Le jeton protégé': 'The protected token',
  "Émis par le processus protégé après un unlock réussi, et connu de sa mémoire seulement. Il ouvre le chat Céline protégé — et rien d'autre.":
    'Issued by the protected process after a successful unlock, and known only to its memory. It opens the protected Céline chat — and nothing else.',
  'Chat protégé': 'Protected chat',
  'Identifiant · session démo': 'Credential · demo session',
  'Le jeton démo': 'The demo token',
  'Émis par la démo publique, valable 30 minutes, propre à son origine. Le processus protégé ne le connaît pas et le refuse (401).':
    'Issued by the public demo, valid for 30 minutes, bound to its origin. The protected process does not know it and rejects it (401).',
  'Chat démo': 'Demo chat',
  'PRÉSENTER UN IDENTIFIANT ›': 'PRESENT A CREDENTIAL ›',
  'Processus protégé · POST /api/shiftguide/unlock':
    'Protected process · POST /api/shiftguide/unlock',
  'Échange un code correct contre une session protégée ; sinon 401, puis 429 au-delà de 10 tentatives par 10 minutes et par IP.':
    'Trades a correct code for a protected session; otherwise 401, then 429 beyond 10 attempts per 10 minutes per IP.',
  'Code requis': 'Code required',
  'Processus protégé · POST /api/celine/chat': 'Protected process · POST /api/celine/chat',
  'Exige une session valide de CE processus (sinon 401), puis applique 60 requêtes par minute et par IP, 30 par session.':
    'Requires a valid session from THIS process (else 401), then applies 60 requests per minute per IP, 30 per session.',
  'Session protégée': 'Protected session',
  'Processus protégé · POST /api/public-demo/session':
    'Protected process · POST /api/public-demo/session',
  "Répond 404 : le processus protégé n'expose pas la démonstration publique, il ne fait que publier l'adresse de l'origine isolée.":
    "Returns 404: the protected process does not expose the public demo; it only publishes the isolated origin's address.",
  'Processus démo · POST /api/shiftguide/unlock': 'Demo process · POST /api/shiftguide/unlock',
  "Répond 404 : l'origine de démonstration n'expose pas la route de déverrouillage protégée.":
    'Returns 404: the demo origin does not expose the protected unlock route.',
  'Processus démo · POST /api/celine/chat': 'Demo process · POST /api/celine/chat',
  'Céline chat (scénarisé)': 'Céline chat (scripted)',
  "Exige un jeton démo. Le fournisseur est scénarisé : aucun appel IA externe, et les limites de chat existantes s'appliquent.":
    'Requires a demo token. The provider is scripted: no external AI call, and the existing chat limits apply.',
  Scripté: 'Scripted',
  'Processus démo · POST /api/public-demo/session': 'Demo process · POST /api/public-demo/session',
  'Crée une session synthétique sans secret : 30 minutes, 12 créations par 10 minutes et par IP, 100 sessions actives au plus (503 au-delà).':
    'Creates a synthetic session with no secret: 30 minutes, 12 creations per 10 minutes per IP, at most 100 active sessions (503 beyond).',
  'Sans secret': 'No secret',
  'Propriété · démo': 'Property · demo',
  'Aucun secret dans la démo': 'No secret in the demo',
  "L'origine de démonstration n'expose pas la route de déverrouillage, n'accède pas à la configuration protégée et fonctionne avec des fixtures synthétiques du dépôt.":
    'The demo origin does not expose the unlock route, cannot reach the protected configuration, and runs on synthetic repository fixtures.',
  'Sans IA externe': 'No external AI',
  'Réponses scénarisées': 'Scripted answers',
  "Le fournisseur de la démo est un script : l'écran garde visibles les mentions « données fictives » et « réponses scénarisées — aucun appel IA externe » tant que la session est active.":
    'The demo provider is a script: the screen keeps the notices “fictional data” and “scripted answers — no external AI call” visible while the session is active.',
  'Jeton non transférable': 'Non-transferable token',
  'Propriété · isolement': 'Property · isolation',
  'Un jeton, un processus': 'One token, one process',
  "Un jeton de démo est propre à son processus et à son origine : le service protégé ne l'accepte pas. La création de sessions est bornée — 12 par 10 minutes et par IP, 100 actives, 30 minutes.":
    'A demo token is bound to its process and origin: the protected service does not accept it. Session creation is capped — 12 per 10 minutes per IP, 100 active, 30 minutes.',
  Borné: 'Capped',
  '401 · REFUSÉ': '401 · DENIED',
  '404 · ABSENT': '404 · MISSING',
  "Que se passe-t-il quand le stockage ou un second onglet s'en mêle ?":
    'What happens when storage or a second tab gets involved?',
  Stockage: 'Storage',
  'Résilience du stockage navigateur : fail-closed, dégradation en mémoire et verrou multi-onglets':
    'Browser storage resilience: fail-closed, in-memory degradation and multi-tab lock',
  Principe: 'Principle',
  'Fermer sur le secret, dégrader sur le reste': 'Fail closed on secrets, degrade the rest',
  Écriture: 'Write',
  'Enregistrement complet': 'Complete record',
  'Session · étape 1': 'Session · step 1',
  'Un enregistrement logique unique': 'A single logical record',
  "Le jeton, la charge utile protégée, l'expiration, la révision de configuration et la révision d'autorité de Céline vivent dans sessionStorage et forment un seul enregistrement : ils s'écrivent ensemble.":
    'The token, protected payload, expiry, configuration revision and Céline authority revision live in sessionStorage and form a single record: they are written together.',
  Relecture: 'Read-back',
  Vérification: 'Verification',
  'Session · étape 2': 'Session · step 2',
  "On relit ce qu'on vient d'écrire": 'We read back what we just wrote',
  "L'unlock relit l'enregistrement pour le vérifier. Une lecture qui lève une exception vaut identifiants absents : jamais une valeur présumée.":
    'The unlock reads the record back to verify it. A read that throws counts as missing credentials: never an assumed value.',
  'Session ouverte': 'Session open',
  'Session · résultat': 'Session · result',
  'Fermer sur le secret': 'Fail closed on secrets',
  "Sans sessionStorage, ProtoCap ne retombe pas sur la mémoire du processus : aucun jeton n'est conservé dans un repli applicatif. Toute opération qui échoue annule les écritures partielles — pas d'interface à moitié déverrouillée.":
    'Without sessionStorage, ProtoCap does not fall back to process memory: no token is kept in an app-level fallback. Any failed operation rolls back partial writes — no half-unlocked interface.',
  'État non sensible': 'Non-sensitive state',
  'Progression · étape 1': 'Progress · step 1',
  'Un état qui ne demande pas le secret': "State that doesn't need the secret",
  "La progression de procédure, l'historique de Céline et la préférence du cockpit passent par la frontière de stockage résiliente : un autre niveau de confiance, donc une autre politique d'échec.":
    'Procedure progress, Céline history and the cockpit preference go through the resilient storage boundary: a different trust level, so a different failure policy.',
  'Miroir mémoire': 'Memory mirror',
  'Bascule si refus': 'Switch if refused',
  'Progression · étape 2': 'Progress · step 2',
  'Un miroir en mémoire': 'An in-memory mirror',
  "L'adaptateur reflète chaque valeur lue ou écrite. Si le navigateur rejette une lecture, une écriture, une suppression ou une énumération (bloqué, indisponible, quota), il bascule sur ce miroir pour la durée de la page.":
    'The adapter mirrors every value read or written. If the browser rejects a read, write, delete or enumeration (blocked, unavailable, quota), it switches to this mirror for the life of the page.',
  'Page seulement': 'Page only',
  Persisté: 'Persisted',
  'Progression · résultat': 'Progress · result',
  'Dégrader sans mentir': 'Degrade without lying',
  "Continuité plutôt que plantage pour un état non sensible — mais sans prétendre à la durabilité : ShiftGuide affiche un avertissement, les changements peuvent être perdus au rechargement. Le repli n'est pas synchronisé entre onglets.":
    'Continuity rather than a crash for non-sensitive state — but no claim of durability: ShiftGuide shows a warning, and changes may be lost on reload. The fallback is not synced across tabs.',
  Avertissement: 'Warning',
  'Enregistrement vérifié': 'Record verified',
  Verrouillé: 'Locked',
  'Rollback · aucun jeton gardé': 'Rollback · no token kept',
  'Mémoire seule': 'Memory only',
  'Avertissement affiché': 'Warning shown',
  'Stockage disponible': 'Storage available',
  'Scénario · stockage OK': 'Scenario · storage OK',
  'Le navigateur répond': 'The browser responds',
  'Session complète vérifiée, progression persistée : le comportement normal.':
    'Full session verified, progress persisted: normal behavior.',
  'Stockage bloqué': 'Storage blocked',
  'Scénario · stockage refusé': 'Scenario · storage refused',
  "Le navigateur refuse d'écrire": 'The browser refuses to write',
  "La session se ferme et se réinitialise ; la progression, elle, continue en mémoire avec un avertissement. Deux niveaux de confiance, deux politiques d'échec assumées.":
    'The session closes and resets; progress, for its part, continues in memory with a warning. Two trust levels, two deliberate failure policies.',
  'Session : fermée': 'Session: closed',
  'Progression : dégradée': 'Progress: degraded',
  'Sans verrou': 'No lock',
  'Scénario · deux onglets, sans verrou': 'Scenario · two tabs, no lock',
  'Lire, modifier, écrire : la course': 'Read, modify, write: the race',
  'Écrire une clé est atomique, mais une mise à jour de progression est lire → modifier → écrire. Deux onglets lisent le même instantané, et le dernier à écrire efface silencieusement le travail du premier.':
    "Writing a key is atomic, but a progress update is read → modify → write. Two tabs read the same snapshot, and the last to write silently erases the first one's work.",
  'Mise à jour perdue': 'Lost update',
  'Avec Web Locks': 'With Web Locks',
  'Scénario · deux onglets, avec verrou': 'Scenario · two tabs, with lock',
  'Un verrou exclusif par origine': 'One exclusive lock per origin',
  "Toute la transaction — lire le document frais, appliquer l'intention, écrire, notifier — s'exécute sous un verrou Web Locks. Sans Web Locks : file FIFO dans la page et avertissement. Local à l'origine : aucune synchronisation entre appareils.":
    'The whole transaction — read the fresh document, apply the intent, write, notify — runs under a Web Locks lock. Without Web Locks: an in-page FIFO queue and a warning. Origin-local: no cross-device sync.',
  Sérialisé: 'Serialized',
  'Révision liée': 'Linked revision',
  'Lit {}': 'Reads {}',
  'Écrit {X}': 'Writes {X}',
  'Écrit {Y}': 'Writes {Y}',
  'Prend le verrou': 'Takes the lock',
  'Lit {} · écrit {X}': 'Reads {} · writes {X}',
  'Attend le verrou…': 'Waits for the lock…',
  'Lit {X} · écrit {X,Y}': 'Reads {X} · writes {X,Y}',
  'ONGLET A': 'TAB A',
  'ONGLET B': 'TAB B',
  PROGRESSION: 'PROGRESS',
  'LA MISE À JOUR X EST PERDUE': 'UPDATE X IS LOST',
  "LE DERNIER ÉCRIVAIN ÉCRASE : B AVAIT LU {} AVANT QUE A N'ÉCRIVE":
    'LAST WRITER WINS: B HAD READ {} BEFORE A WROTE',
  'X ET Y SONT CONSERVÉES': 'X AND Y ARE KEPT',
  'B ATTEND, PUIS LIT UN DOCUMENT FRAIS : LIRE → ÉCRIRE EST SÉRIALISÉ':
    'B WAITS, THEN READS A FRESH DOCUMENT: READ → WRITE IS SERIALIZED',
  'Combien préparer, et où en est-on ?': 'How much to prep, and where are we?',
  "Packing : politiques d'arrondi et cockpit de déclarations, calcul réel":
    'Packing: rounding policies and declaration cockpit, real calculation',
  Calcul: 'Math',
  'Entiers sûrs · dépassement refusé': 'Safe integers · overflow refused',
  'Sans dépassement': 'No overrun',
  'Carton complet': 'Full carton',
  'Palette complète': 'Full pallet',
  'QUANTITÉ À PRÉPARER': 'QUANTITY TO PREPARE',
  'UNITÉS PAR CARTON': 'UNITS PER CARTON',
  'CARTONS PAR PALETTE': 'CARTONS PER PALLET',
  CADENCE: 'RATE',
  démo: 'demo',
  'logique de packing.ts · même arithmétique': 'packing.ts logic · same arithmetic',
  'Politique · sans dépassement': 'Policy · no overrun',
  "Exactement la quantité demandée : palettes complètes, cartons complets, puis unités isolées. Aucun article de trop — au prix d'un carton entamé.":
    'Exactly the requested quantity: full pallets, full cartons, then loose units. Not one extra item — at the cost of an opened carton.',
  'Écart 0': 'Delta 0',
  'Politique · carton complet': 'Policy · full carton',
  "Arrondit le reste au carton supérieur : plus de carton entamé, avec un léger écart positif. C'est la recommandation par défaut, sauf si l'écart est nul — alors la politique exacte suffit.":
    'Rounds the remainder up to the next carton: no opened carton, with a slight positive delta. This is the default recommendation, unless the delta is zero — then the exact policy suffices.',
  Recommandée: 'Recommended',
  'Politique · palette complète': 'Policy · full pallet',
  "Arrondit à la palette entière : simple à expédier, mais l'écart peut être important. Utile seulement quand la palette est l'unité de décision.":
    'Rounds to the whole pallet: simple to ship, but the delta can be large. Useful only when the pallet is the unit of decision.',
  'Écart maximal': 'Maximum delta',
  'cliquer pour choisir le plan': 'click to choose the plan',
  RECOMMANDÉ: 'RECOMMENDED',
  ' U PRÉPARÉES  ·  ÉCART ': ' U PREPARED  ·  DELTA ',
  'Démonstration · cockpit de déclarations': 'Demo · declaration cockpit',
  'Une déclaration à la fois, jamais au-delà du plan':
    'One declaration at a time, never beyond the plan',
  "Chaque déclaration (palette, carton, unité) s'ajoute à l'historique ; celle qui dépasserait le plan est refusée, la dernière peut être annulée. Toute l'arithmétique reste en entiers sûrs, et le temps restant est un plafond entier.":
    'Each declaration (pallet, carton, unit) is added to the history; one that would exceed the plan is refused, and the last one can be undone. All arithmetic stays in safe integers, and time remaining is an integer ceiling.',
  Événements: 'Events',
  'COCKPIT · DÉCLARATIONS': 'COCKPIT · DECLARATIONS',
  HISTORIQUE: 'HISTORY',
  'Refusé · dépasserait le plan de ': 'Refused · would exceed the plan by ',
  'Déclaré · +': 'Declared · +',
  'Annulé · −': 'Undone · −',
  'Rien à annuler': 'Nothing to undo',
  'Suivi remis à zéro': 'Tracking reset',
  '+1 palette': '+1 pallet',
  'Déclarer une palette': 'Declare a pallet',
  'Déclarer un carton': 'Declare a carton',
  '+1 unité': '+1 unit',
  'Déclarer une unité': 'Declare a unit',
  Annuler: 'Undo',
  'Annuler la dernière déclaration': 'Undo the last declaration',
  'Remise à zéro': 'Reset',
  'Remettre le suivi à zéro': 'Reset tracking',
  '  +  1 PARTIELLE': '  +  1 PARTIAL',
  ' U   ·   RESTE ': ' U   ·   LEFT ',
  ' MIN RESTANTES À ': ' MIN LEFT AT ',
  'PLAN ATTEINT · RIEN À DÉCLARER': 'PLAN REACHED · NOTHING TO DECLARE',
  "Qu'a le droit de devenir une demande ?": 'What is a request allowed to become?',
  Logistique: 'Logistics',
  "Logistics Call : machine à états d'une demande et transitions autorisées":
    "Logistics Call: a request's state machine and allowed transitions",
  'Un statut terminal ne se rouvre pas': 'A terminal status never reopens',
  'En attente': 'On hold',
  EN: 'ON',
  ATTENTE: 'HOLD',
  Vu: 'Seen',
  VU: 'SEEN',
  'En cours': 'Underway',
  'EN COURS': 'UNDERWAY',
  Récupéré: 'Picked up',
  RÉCUPÉRÉ: 'PICKED UP',
  Annulé: 'Canceled',
  ANNULÉ: 'CANCELED',
  'Statut initial': 'Initial status',
  'Une demande naît en attente. Elle peut passer à Vu, En cours, Récupéré ou Annulé : quatre issues, dont deux terminales.':
    'A request starts on hold. It can move to Seen, Underway, Picked up or Canceled: four outcomes, two of them terminal.',
  '4 issues': '4 outcomes',
  'Statut intermédiaire': 'Intermediate status',
  'La demande a été vue mais pas encore prise en charge. Elle peut passer à En cours, Récupéré ou Annulé — jamais revenir à En attente.':
    'The request has been seen but not yet taken on. It can move to Underway, Picked up or Canceled — never back to On hold.',
  '3 issues': '3 outcomes',
  'La prise en charge a commencé. Seules deux sorties restent possibles : Récupéré ou Annulé. Un statut ne recule pas.':
    'Handling has started. Only two exits remain: Picked up or Canceled. A status never moves back.',
  '2 issues': '2 outcomes',
  'Statut terminal': 'Terminal status',
  "Fin heureuse du cycle. Le statut est terminal : plus aucune transition n'est acceptée, et l'heure de fin (completedAt) est écrite.":
    'The happy end of the cycle. The status is terminal: no further transition is accepted, and the end time (completedAt) is written.',
  'Fin par annulation. Terminal lui aussi : une demande annulée ne se rouvre pas, et son heure de fin est écrite.':
    'End by cancellation. Also terminal: a canceled request never reopens, and its end time is written.',
  'CLIQUER UN STATUT POUR TENTER LA TRANSITION': 'CLICK A STATUS TO TRY THE TRANSITION',
  'ÉTAT ACTUEL  ›  ': 'CURRENT STATE  ›  ',
  'Transition autorisée · ': 'Transition allowed · ',
  ' · completedAt écrit': ' · completedAt written',
  'Refusé · ': 'Refused · ',
  ' est terminal : aucune sortie possible': ' is terminal: no exit possible',
  'Refusé · un statut ne recule jamais (': 'Refused · a status never moves back (',
  Réinitialiser: 'Reset',
  'Remettre la demande en attente': 'Put the request back on hold',
  Persistance: 'Persistence',
  'Stockage · lineops.logistics.requests.v9': 'Storage · lineops.logistics.requests.v9',
  "Une écriture est relue avant d'être crue": 'A write is read back before it is trusted',
  "La demande vit dans le navigateur. Chaque écriture est vérifiée par relecture, et l'état de la persistance (prête, mémoire, migration en attente, récupération, lecture seule, dégradée, échec d'écriture) est exposé plutôt que masqué. Aucun envoi vers un autre poste.":
    'The request lives in the browser. Every write is verified by read-back, and the persistence state (ready, memory, migration pending, recovery, read-only, degraded, write failure) is exposed rather than hidden. Nothing is sent to another station.',
  'Cette validité est-elle fiable ?': 'Is this validity reliable?',
  Péremption: 'Expiry',
  "Expiry Check : dates locales, changements d'heure et statuts de péremption":
    'Expiry Check: local dates, clock changes and expiry statuses',
  'Calendrier local · jamais N × 24 h': 'Local calendar · never N × 24 h',
  'Heure valide · décalage +02:00': 'Valid time · offset +02:00',
  "Refusée · cette heure n'existe pas": 'Refused · this time does not exist',
  "— rien n'est enregistré": '— nothing is saved',
  'Ambiguë · cette heure existe deux fois': 'Ambiguous · this time occurs twice',
  '— à choisir ci-dessous': '— choose below',
  '24/10/2026 12:00  ·  validité : 1 jour': '24/10/2026 12:00  ·  validity: 1 day',
  'Jour calendaire local · calendar-days-v1': 'Local calendar day · calendar-days-v1',
  'Illisible → « Date à vérifier »': 'Unreadable → “Date to check”',
  '— statut unknown · jamais présumé valide': '— status unknown · never assumed valid',
  'Heure normale': 'Normal time',
  'Scénario · saisie ordinaire': 'Scenario · ordinary entry',
  'Un instant, un fuseau nommé': 'An instant, a named time zone',
  "Une heure locale valide est convertie en instant UTC par Temporal, à partir d'un fuseau nommé du navigateur — jamais avec un décalage codé en dur. L'exemple utilise Europe/Paris.":
    'A valid local time is converted to a UTC instant by Temporal, from a named browser time zone — never with a hard-coded offset. The example uses Europe/Paris.',
  'Fuseau nommé': 'Named time zone',
  'Heure inexistante': 'Nonexistent time',
  "Scénario · changement d'heure de printemps": 'Scenario · spring clock change',
  "Le trou du changement d'heure": 'The DST gap',
  "Le 29 mars 2026, 02:00 devient 03:00 : 02:30 n'existe pas. La saisie est refusée avec un message clair (« corrigez la saisie ») au lieu d'être décalée en silence.":
    'On March 29, 2026, 02:00 becomes 03:00: 02:30 does not exist. The entry is refused with a clear message (“correct the entry”) instead of being silently shifted.',
  'Heure en double': 'Repeated time',
  "Scénario · changement d'heure d'automne": 'Scenario · fall clock change',
  "L'heure qui existe deux fois": 'The hour that occurs twice',
  "Le 25 octobre 2026, 02:30 se produit deux fois. ProtoCap n'en choisit aucune : l'utilisateur précise explicitement son décalage UTC, le premier ou le second.":
    'On October 25, 2026, 02:30 occurs twice. ProtoCap picks neither: the user explicitly states the UTC offset, the first or the second.',
  'Choix explicite': 'Explicit choice',
  '+1 jour': '+1 day',
  'Scénario · validité en jours': 'Scenario · validity in days',
  "Un jour n'est pas 24 heures": 'A day is not 24 hours',
  "La validité compte des jours du calendrier dans le fuseau de la déclaration, pas N × 24 heures. Le 25 octobre 2026 dure 25 heures : ajouter 24 h décalerait l'expiration d'une heure.":
    "Validity counts calendar days in the declaration's time zone, not N × 24 hours. October 25, 2026 lasts 25 hours: adding 24 h would shift the expiry by an hour.",
  'Donnée incohérente': 'Inconsistent data',
  'Scénario · donnée illisible': 'Scenario · unreadable data',
  "Le doute n'est jamais « valide »": 'Doubt is never “valid”',
  'Les instants stockés exigent un décalage explicite et un vrai calendrier ISO ; Date.parse est jugé trop permissif. Une donnée incohérente donne « Date à vérifier », jamais un statut rassurant.':
    'Stored instants require an explicit offset and a real ISO calendar; Date.parse is deemed too permissive. Inconsistent data yields “Date to check”, never a reassuring status.',
  'SAISIE LOCALE': 'LOCAL ENTRY',
  RÉSOLUTION: 'RESOLUTION',
  'INSTANT STOCKÉ (UTC)': 'STORED INSTANT (UTC)',
  'Le premier · +02:00': 'The first · +02:00',
  'Le second · +01:00': 'The second · +01:00',
  'Choisir : ': 'Choose: ',
  "25/10 11:00 local · faux d'une heure": '25/10 11:00 local · off by an hour',
  'CALENDRIER LOCAL': 'LOCAL CALENDAR',
  '25/10 12:00 local · 25 h écoulées': '25/10 12:00 local · 25 h elapsed',
  'STATUT DE PÉREMPTION': 'EXPIRY STATUS',
  Expiré: 'Expired',
  "Le temps restant est nul ou négatif : l'élément est expiré, la ligne passe en non conforme.":
    'Time remaining is zero or negative: the item is expired, and the line becomes nonconforming.',
  'Bientôt expiré': 'Expiring soon',
  "Moins de 48 heures restantes : l'élément est à surveiller, la ligne passe en statut watch.":
    'Under 48 hours remaining: the item is on watch, and the line moves to watch status.',
  "Plus de 48 heures de validité : l'élément est conforme.":
    'Over 48 hours of validity: the item is conforming.',
  'Date à vérifier': 'Date to check',
  'incohérent › unknown': 'inconsistent › unknown',
  'Donnée incohérente, fuseau invalide ou règle de validité inconnue : le statut est inconnu — jamais présumé valide.':
    'Inconsistent data, invalid time zone or unknown validity rule: the status is unknown — never assumed valid.',
  EXPIRÉ: 'EXPIRED',
  'BIENTÔT EXPIRÉ': 'EXPIRING SOON',
  'RESTE ': 'LEFT ',
  'STATUT DE LA LIGNE  ›  ': 'LINE STATUS  ›  ',
  'Heures de validité restantes': 'Validity hours remaining',
  'Comment sait-on que ça tient ?': 'How do we know it holds?',
  Qualité: 'Quality',
  'Qualité : porte locale, porte CI et preuve de production':
    'Quality: local gate, CI gate and production proof',
  Preuve: 'Proof',
  'CI ≠ déploiement · SHA vérifié': 'CI ≠ deployment · SHA verified',
  Syntaxe: 'Syntax',
  'Serveur · shared': 'Server · shared',
  'Étape locale · 1 / 5': 'Local step · 1 / 5',
  'Vérification de syntaxe': 'Syntax check',
  'Contrôle de syntaxe JavaScript du serveur, du code partagé et des scripts qualité : la première barrière, la plus rapide.':
    'JavaScript syntax check of the server, shared code and quality scripts: the first, fastest barrier.',
  'Tests Node': 'Node tests',
  'Dossier tests/': 'tests/ folder',
  'Étape locale · 2 / 5': 'Local step · 2 / 5',
  'La suite de tests Node': 'The Node test suite',
  'La suite de tests du serveur et des contrats partagés, exécutée par le runner Node natif.':
    'The test suite for the server and shared contracts, run by the native Node runner.',
  'Seuils 60/50/50/60': 'Limits 60/50/50/60',
  'Étape locale · 3 / 5': 'Local step · 3 / 5',
  'Couverture avec seuils bloquants': 'Coverage with blocking thresholds',
  'Suite Vitest ciblée sur le risque, avec seuils V8 bloquants : 60 % instructions, 50 % branches, 50 % fonctions, 60 % lignes. Le dénominateur reste volontairement stable, et les modules critiques ont des objectifs par fichier (90 / 85 %).':
    'Risk-targeted Vitest suite, with blocking V8 thresholds: 60% statements, 50% branches, 50% functions, 60% lines. The denominator is deliberately kept stable, and critical modules have per-file targets (90 / 85%).',
  Seuils: 'Limits',
  'Async typé': 'Typed async',
  'Étape locale · 4 / 5': 'Local step · 4 / 5',
  'Lint, règles asynchrones typées': 'Lint, typed async rules',
  'ESLint, y compris les règles asynchrones sensibles aux types pour le TypeScript applicatif.':
    'ESLint, including type-aware async rules for the application TypeScript.',
  'Étape locale · 5 / 5': 'Local step · 5 / 5',
  'Build de production': 'Production build',
  "Le build TypeScript et Vite de production : la boucle de retour normale d'un développeur.":
    "The production TypeScript and Vite build: a developer's normal feedback loop.",
  Couverture: 'Coverage',
  'Globale · serveur': 'Global · server',
  'Étape CI · 1 / 6': 'CI step · 1 / 6',
  'Rapports honnêtes': 'Honest reports',
  "check:ci ajoute la couverture frontend globale (descriptive, sans seuil) et la couverture serveur : rendre visible ce qui n'est pas mesuré plutôt que de gonfler un pourcentage.":
    'check:ci adds global frontend coverage (descriptive, no threshold) and server coverage: making visible what is not measured rather than inflating a percentage.',
  Descriptif: 'Descriptive',
  'Étape CI · 2 / 6': 'CI step · 2 / 6',
  'Prouver que les tests détectent': 'Proving the tests detect',
  'Trois mutations temporaires — transition Logistics inversée, jour calendaire en trop sur Expiry, vérification post-écriture ignorée — et les tests ciblés doivent échouer. Un mutant qui survit fait échouer check:ci.':
    'Three temporary mutations — Logistics transition reversed, an extra calendar day on Expiry, post-write verification skipped — and the targeted tests must fail. A surviving mutant fails check:ci.',
  Restaurés: 'Restored',
  'Smoke runtime': 'Runtime smoke',
  'Étape CI · 3 / 6': 'CI step · 3 / 6',
  'Démarrer, pas seulement construire': 'Start, not just build',
  "Une image qui se construit ne prouve pas qu'elle démarre : le smoke runtime Docker est un contrôle de workflow à part.":
    'An image that builds does not prove it starts: the Docker runtime smoke is a separate workflow check.',
  'Étape CI · 4 / 6': 'CI step · 4 / 6',
  'Navigateurs, sans retry complaisant': 'Browsers, no lenient retry',
  "Serveurs de test synthétiques et hermétiques : aucun appel DeepSeek, aucun secret. Un retry capture une trace, mais failOnFlakyTests fait échouer un test qui ne passe qu'au second essai.":
    'Synthetic, hermetic test servers: no DeepSeek call, no secret. A retry captures a trace, but failOnFlakyTests fails a test that only passes on the second try.',
  Accessibilité: 'Accessibility',
  'Étape CI · 5 / 6': 'CI step · 5 / 6',
  'Détecter, sans prétendre certifier': 'Detect, without claiming to certify',
  "La porte axe bloque les constats WCAG A/AA d'impact critique ou sérieux. C'est un détecteur de régressions, pas une déclaration de conformité.":
    'The axe gate blocks WCAG A/AA findings of critical or serious impact. It is a regression detector, not a conformance statement.',
  'Analyse statique': 'Static analysis',
  'Étape CI · 6 / 6': 'CI step · 6 / 6',
  'Analyse de sécurité': 'Security analysis',
  "L'analyse CodeQL accompagne le Quality Gate comme preuve requise sur le commit fusionné.":
    'CodeQL analysis accompanies the Quality Gate as required proof on the merged commit.',
  '03 · PRODUCTION  ›  APRÈS FUSION SUR MAIN': '03 · PRODUCTION  ›  AFTER MERGE TO MAIN',
  'Merge sur main': 'Merge to main',
  'Gate vert': 'Green gate',
  'Jamais depuis un main cassé': 'Never from a broken main',
  'Le Quality Gate doit être vert avant la fusion, et le SHA de fusion est noté : on ne poursuit pas une release depuis un main cassé.':
    'The Quality Gate must be green before the merge, and the merge SHA is recorded: no release proceeds from a broken main.',
  Déploiement: 'Deployment',
  'Le bon commit, en SUCCESS': 'The right commit, at SUCCESS',
  "Railway doit créer un déploiement pour ce SHA exact et atteindre le statut SUCCESS avant que l'on revendique quoi que ce soit.":
    'Railway must create a deployment for this exact SHA and reach SUCCESS status before anything is claimed.',
  Prêt: 'Ready',
  'La santé du runtime': 'Runtime health',
  "Le healthcheck de production est /api/ready : il doit répondre 200. Cela prouve que le runtime est prêt — pas que c'est la bonne version.":
    'The production healthcheck is /api/ready: it must return 200. That proves the runtime is ready — not that it is the right version.',
  'Même SHA': 'Same SHA',
  'Commit = déployé': 'Commit = deployed',
  'La preuve qui compte': 'The proof that counts',
  'La preuve de clôture est invalide si Railway sert un commit plus ancien, même avec /api/ready sain : la santé prouve la disponibilité, la correspondance du commit prouve que le code validé est celui qui tourne.':
    'The closing proof is invalid if Railway serves an older commit, even with a healthy /api/ready: health proves availability; the commit match proves the validated code is what runs.',
  'SHA vérifié': 'SHA verified',
  'Chaque jour 06:17 UTC': 'Daily at 06:17 UTC',
  'Une sonde qui ne consomme rien': 'A probe that consumes nothing',
  "Sonde externe en GET seulement, sans secret : elle ne touche ni l'unlock, ni la création de session démo, ni le chat — donc aucun essai de code, aucune session et aucun jeton d'IA consommés. Elle vérifie aussi la frontière entre origine protégée et origine démo.":
    'External GET-only probe, with no secret: it touches neither the unlock, demo session creation nor the chat — so no code attempts, sessions or AI tokens are used. It also checks the boundary between the protected and demo origins.',
  'Lecture seule': 'Read-only',
  'un CI vert ne prouve pas un déploiement : seul le SHA servi le prouve':
    'a green CI does not prove a deployment: only the served SHA does',
  'Local navigateur': 'Local browser',
  déterministe: 'deterministic',
  Intention: 'Intent',
  Invalide: 'Invalid',
  'SERVEUR ÉCRIT': 'SERVER WRITES',
  AUCUN: 'NO',
  IDENTIFIANT: 'CREDENTIAL',
  JETON: 'TOKEN',
  PROTÉGÉ: 'PROTECTED',
  DÉMO: 'DEMO',
  Complet: 'Complete',
  Vérifiée: 'Verified',
  'Non sensible': 'Non-sensitive',
  'Si refus': 'If refused',
  'Stockage OK': 'Storage OK',
  "B AVAIT LU {} AVANT QUE A N'ÉCRIVE": 'B HAD READ {} BEFORE A WROTE',
  'X ET Y CONSERVÉES': 'X AND Y KEPT',
  'B ATTEND, PUIS LIT UN DOCUMENT FRAIS': 'B WAITS, THEN READS A FRESH DOC',
  QUANTITÉ: 'QUANTITY',
  'CTN / PALETTE': 'CTN / PALLET',
  'ÉCART 0': 'DELTA 0',
  ' U  ·  RESTE ': ' U  ·  LEFT ',
  'PLAN ATTEINT': 'PLAN REACHED',
  'Autorisée · ': 'Allowed · ',
  ' est terminal': ' is terminal',
  'Refusé · un statut ne recule jamais': 'Refused · a status never moves back',
  'Ambiguë · existe deux fois': 'Ambiguous · occurs twice',
  '24/10/2026 12:00 · 1 jour': '24/10/2026 12:00 · 1 day',
  'Jour calendaire · calendar-days-v1': 'Calendar day · calendar-days-v1',
  '— unknown · jamais présumé valide': '— unknown · never assumed valid',
  Normale: 'Normal',
  Inexistante: 'Nonexistent',
  'En double': 'Repeated',
  Incohérente: 'Inconsistent',
  "N × 24 H › 25/10 11:00 · FAUX D'1 H": 'N × 24 H › 25/10 11:00 · OFF BY 1 H',
  'CALENDRIER › 25/10 12:00 · 25 H ÉCOULÉES': 'CALENDAR › 25/10 12:00 · 25 H ELAPSED',
  'Couv.': 'Cov.',
  '03 · PRODUCTION  ›  APRÈS FUSION': '03 · PRODUCTION  ›  AFTER MERGE',
  '<tspan class="note-k">PRINCIPE  </tspan><tspan>UN CI VERT NE PROUVE PAS</tspan>':
    '<tspan class="note-k">PRINCIPLE  </tspan><tspan>A GREEN CI DOES NOT PROVE</tspan>',
  'UN DÉPLOIEMENT : SEUL LE SHA SERVI LE PROUVE': 'A DEPLOYMENT: ONLY THE SERVED SHA PROVES IT',
  ' PALETTES PLEINES': ' FULL PALLETS',
  ' PALETTE PLEINE': ' FULL PALLET',
  ambigu: 'unclear',
  valide: 'valid',
  invalide: 'invalid',
  politique: 'policy',
  principe: 'principle',
  'Statut · ': 'Status · ',
  'Progression · ': 'Progress · ',
  'PROGRESSION · LOCALSTORAGE': 'PROGRESS · LOCALSTORAGE',
};

export default dictionary;
